var _uuid=0,_instance;function CloudSpectrum(a){this.cfg=this.merge({node:"",width:600,height:400,mode:"edit"},a);this.eventHandlers=[];this.cache={};this._init()}
CloudSpectrum.prototype={constructor:CloudSpectrum,_init:function(){var a=this,c=a.cfg,b=c.width,e=c.height;node=a.dom().get(c.node);node.width(b);node.height(e);var f="cloudSpectrum-"+a._guid();"edit"==c.mode?(node.html('<div class="ui-cloudSpectrum" style="width:'+b+"px; height:"+e+'px; overflow:auto"><div id="'+f+'"></div><div id="cp-preview-panel"></div><div id="cp-preview-btn">预览</div></div>'),a.paper=Raphael(f,3*b,2*e)):(node.html('<div class="ui-cloudSpectrum" style="width:'+b+"px; height:"+
e+'px; overflow:hidden"><div id="'+f+'"></div></div>'),a.paper=Raphael(f,b,e));Raphael.fn.connection=function(b,c,e){var g;b.line&&(b.from&&b.to)&&(g=b,b=g.from,c=g.to);var f=b.getBBox(),k=c.getBBox(),h=[{x:f.x+f.width/2,y:f.y+f.height/2},{x:k.x+k.width/2,y:k.y+k.height/2},{x:k.x+k.width/2,y:k.y+k.height/2}],f=(h[1].x+h[0].x)/2,k=(h[1].y+h[0].y)/2,h=["M",h[0].x,h[0].y,"L",h[1].x,h[1].y].join();if(g&&g.line)g.line.toBack().attr({path:h}),g.lineNode.attr({x:f,y:k,cx:f,cy:k});else return{line:this.path(h).toBack().attr({stroke:"#C6D9EC",
"stroke-width":"2px",fill:"none"}),from:b,to:c,lineNode:a.paper.set().push(this.circle(f,k,8).attr({fill:"#BED8EC",stroke:"#C6D9EC"}),this.text(f,k,"?").attr({stroke:"#fff",cursor:"pointer"})),lineOpt:e}};if("edit"==c.mode){var h=1,l=a.dom().get("#cp-preview-btn");l.bind("click",function(){var c=a.dom().get("#cp-preview-panel");h?(c.show(),l.html("编辑"),c.html(""),_instance&&(new CloudSpectrum({node:"#cp-preview-panel",width:b,height:e,mode:"view"})).render(_instance.preview()),h=0):(c.hide(),c.html(""),
l.html("预览"),h=1)})}},render:function(a){var c,b;function e(){if(this.data("setIndex")&&void 0!=this.data("dataIndex")){E=s[this.data("setIndex")];F=v[this.data("dataIndex")];var w=E.getBBox();b=c=void 0;C=!0;c=w.x+w.width/2;b=w.y+w.height/2}}function f(w,n){if(C){var d=c+w,a=b+n,e={x:d,y:a,cx:d,cy:a};G||(E.attr(e),F.theta=Raphael.rad(Raphael.angle(d,a,q.w/2,q.h/2)),F.radius=g._computeLength(q.w/2,q.h/2,d,a),G=!0,setTimeout(function(){G=!1},40));for(d=A.length;d--;)k.connection(A[d]);k.safari()}}
function h(){C&&(C=!1)}function l(b,n,d){d=x[b.id];if(0<n.length)for(var a=0;a<n.length;a++)if(n[a]){var c=n[a],g=c.id;A.push(k.connection(s[d.index],s[x[g].index],{pid:b.id,id:g}));l(c,c.childNodes)}}function m(b,n){if(n.length){var d=n.length;g._getAverageWeight(n);if(void 0!==b.theta){var a=Math.PI/d;2==y&&(a=Math.PI/10);3==y&&a>Math.PI/24&&(a=Math.PI/24);for(var c=a*(d-1)/2-b.theta,e=0;e<d;e++)B(n[e],b,3.5*y*z,-c+e*a)}else for(a=2*Math.PI/d,e=0;e<d;e++)B(n[e],b,3.5*y*z,e*a)}}function B(b,a,d,
c){if(!x[b.id]){var e=v.length,f=g.shapes.length;a="edit"==u.mode?g._polarToXY(a,d,c):g._polarToXY(a,b.radius,b.theta);var h;h="edit"==u.mode?r("3",a,z).attr({fill:b.color,stroke:b.color}).data("setIndex",f):r(b.shape+"",a,z).attr({fill:b.color,stroke:b.color}).data("setIndex",f);s.push(k.set().push(h,k.text(a[0],a[1],b.name).attr(I).data("setIndex",f).data("dataIndex",e)));x[b.id]={x:a[0],y:a[1],theta:c,index:f};b.theta=c;b.radius=d;v.push(g.clone(b))}}function r(b,a,d){switch(b){case "1":d=k.rect(a[0]-
d,a[1]-d,2*d,2*d);break;case "2":d=k.ellipse(a[0],a[1],d,0.6*d);break;case "3":d=k.circle(a[0],a[1],d);break;case "4":b=a[0];a=a[1];var c=d*Math.cos(36*Math.PI/180),e=d*Math.sin(36*Math.PI/180),g=d*Math.cos(18*Math.PI/180),f=d*Math.sin(18*Math.PI/180);d=["M",b-e,a+c,"L",b+e,a+c,"L",b+g,a-f,"L",b,a-d,"L",b-g,a-f].join(" ");d=k.path(d);break;case "5":b=a[0];a=a[1];c=d*Math.cos(Math.PI/3);e=d*Math.sin(Math.PI/3);d=["M",b-e,a+c,"L",b+e,a+c,"L",b,a-d].join(" ");d=k.path(d);break;case "6":b=a[0];a=a[1];
c=d*Math.cos(Math.PI/6);e=d*Math.sin(Math.PI/6);d=["M",b-e,a+c,"L",b+e,a+c,"L",b+d,a,"L",b+e,a-c,"L",b-e,a-c,"L",b-d,a].join(" ");d=k.path(d);break;case "7":d=k.rect(a[0]-d,a[1]-d,2*d,2*d,10);break;default:d=k.circle(a[0],a[1],d)}return d}var g=this,u=g.cfg;g.dom();var k=g.paper;g.connections=[];g.shapes=[];g.flatData=[];g.data=a;g.cache={};g.cache.w=u.width;g.cache.h=u.height;g.objects={};var s=g.shapes,q=g.cache,x=g.objects,v=g.flatData,I={fill:"#fff","font-size":"14px","font-weight":"400"},p=Math.round(Math.max(q.w,
q.h)/6),z=Math.round(p/4);g.circleRadius=z;var p=[],t=[],y=1;p.push(a);(function(b){for(var a=0;0<b.length;){var d=b.shift();if(d)if(0==d.parent){var c=q.w/2,e=q.h/2,f=g.shapes.length,h=r(d.shape+"",[c,e],1.2*z);h.attr({fill:d.color,stroke:d.color}).data("setIndex",f);s.push(k.set().push(h,k.text(c,e,d.name).attr(I).data("setIndex",f).data("dataIndex",f)));x[d.id]={x:c,y:e,theta:0,index:0};d.theta=0;d.radius=0;v.push(g.clone(d));0<d.childNodes.length&&t.push(d.childNodes.length);m({x:c,y:e},d.childNodes);
b=b.concat(d.childNodes);y++}else c=x[d.id],a==t[0]?(t.shift(),a=0,y++,t.push(d.childNodes.length)):t[1]=t[1]?t[1]+d.childNodes.length:d.childNodes.length,m(c,d.childNodes),b=b.concat(d.childNodes),a++}})(p);for(var C=!1,E,F,G=!1,p=0,H=s.length;p<H;p++){Raphael.getColor();var D=s[p];D.attr({cursor:"pointer"});"edit"==u.mode&&(D.attr({cursor:"move"}),D.drag(f,e,h));(function(b){b.mouseover(function(){b.stop().animate({transform:"s1.2 1.2"},500,"backOut")}).mouseout(function(){b.stop().animate({transform:""},
500,"backOut")});"view"==u.mode?b.click(function(b){var a=this.data("dataIndex");g._publish("nodeClick",{x:b.pageX,y:b.pageY,id:v[a].id})}):b.dblclick(function(b){var a=this.data("dataIndex");g._publish("nodeClick",{x:b.pageX,y:b.pageY,id:v[a].id})})})(D)}var A=[];l(a,a.childNodes);p=0;for(H=A.length;p<H;p++)a=A[p],function(b,a){b&&(b.mouseover(function(){b.stop().animate({transform:"s1.2 1.2"},500,"backOut")}).mouseout(function(){b.stop().animate({transform:""},500,"backOut")}),b.click(function(b){g._publish("relationClick",
{x:b.pageX,y:b.pageY,id:a.id,parentId:a.pid})}))}(a.lineNode,a.lineOpt)},save:function(){for(var a=[],c=this.flatData.length-1;0<=c;c--)a.push(this.flatData[c]);return a},preview:function(){function a(c){for(var f=0,h=c.length;f<h;f++)for(var l=c[f],m=0;m<b.length;m++)l.id==b[m].id&&(l.theta=b[m].theta,l.radius=b[m].radius),a(l.childNodes)}var c=this.data,b=this.flatData;a([c]);console.log(c);return c},on:function(a,c){this.eventHandlers[a]=c},_publish:function(a,c){var b=this.eventHandlers;b[a]&&
b[a].call(null,c)},_guid:function(){return++_uuid},_polarToXY:function(a,c,b){a=this.cache;var e=a.h/2;return[a.w/2+c*Math.cos(b),e+c*Math.sin(b)]},_computeLength:function(a,c,b,e){return Math.sqrt((a-b)*(a-b)+(c-e)*(c-e))},_getAverageWeight:function(a){if(!a.length)return 0;for(var c=0,b=0,e=a.length;b<e;b++)c+=a[b].weight;return c/a.length},merge:function(a,c){return c},clone:function(a){var c={},b;for(b in a)"[object Array]"==Object.prototype.toString.call(a[b])?c[b]=[]:c[b]=a[b];return c},util:{substitute:function(a,
c){return"[object String]"!==Object.prototype.toString.call(a)?"":"[object Object]"===Object.prototype.toString.call(c)&&"isPrototypeOf"in c?a.replace(/\{([^{}]+)\}/g,function(b,a){var f=c[a];return void 0!==f?""+f:""}):a}},dom:function(){function a(){this.elements=[];this.handlers={}}function c(){this.handlers={}}a.prototype={constructor:a,_events:[],get:function(b,a){var c;if("string"==typeof b)if(c=b,"#"==c.slice(0,1))c=document.getElementById(c.slice(1)),this.elements.push(c);else if(document.querySelectorAll)this.elements.concat(document.querySelectorAll(c,
a.elements));else for(var h=document.body.getElementsByTagName("*"),l=0,m=h.length;l<m;l++)-1!=c.indexOf(h[l].className)&&this.elements.push(h[l]);else this.elements.push(this);return this},each:function(b){for(var a=0,c=this.elements.length;a<c;a++)b.call(this,this.elements[a],a);return this},css:function(b,a){if(a)this.each(function(c){c.style[b]=a});else return this.elements[0].style[b]},width:function(b){return b?(this.elements[0].style.width=b,this):this.elements[0].offsetWidth},height:function(b){return b?
(this.elements[0].style.height=b,this):this.elements[0].offsetHeight},html:function(b){this.elements[0].innerHTML=b},show:function(){this.each(function(b){b.style.display="block"})},hide:function(){this.each(function(b){b.style.display="none"})},ua:{ie:0>navigator.userAgent.indexOf("IE")?!1:!0,firefox:0>navigator.userAgent.indexOf("Firefox")?!1:!0,chrome:0>navigator.userAgent.indexOf("Chrome")?!1:!0},bind:function(b,a){function c(a){a=a||window.event;var e=new h(a);e.type=a.type;e.target=a.target||
a.srcElement;e.pageX=a.clientX||a.pageX;e.pageY=a.clientY||a.pageY;e.button=a.button&1?1:a.button&2?3:a.button&4?2:0;l._events[b].call(l,e)}function h(a){this.eve=a}var l=this;this._events[b]=a;for(var m=0,B=this.elements.length;m<B;m++){var r=this.elements[m];r.addEventListener?r.addEventListener(b,c,!1):element.attachEvent&&r.attachEvent("on"+b,c)}return this},triggle:function(a,c){this.each(this._elements,function(f,h){h.fireEvent?h.fireEvent(a,c):h.dispatchEvent(event)&&h.dispatchEvent(a,c)})}};
c.prototype={constructor:c,on:function(a,c){this.handlers[a]=[]},fire:function(){event.target||(event.target=this);if(this.handlers[event.type instanceof Array])for(var a=this.handlers[event.type],c=0,f=a.length;c<f;c++)a[c](event)},removeHandler:function(a,c){if(this.handlers[a]instanceof Array)for(var f=this.handlers[a],h=0;h<len&&f[h]!==c;h++)f.splice(h,1)}};return new a}};
